### ISSUE TITLE
Appears to be a bug in Version 2.9.0 No value passed for parameter 'forPrint'

### ISSUE THREAD

**Issue by Daniel-Harding** [ScerIO/packages.flutter#573]
**Describe the bug**
Execution failed for task ':pdfx:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

**To Reproduce**
Compiling using VS Code with Android SDK 35 and Java 21... if I use pdfx version 2.8.0 no error but if I change to version 2.9.0 in pubspec.yaml, I get the error message above when compiling.

**Expected behavior**
Expected it to compile with no error messages.

**Screenshots**

![Image](https://github.com/user-attachments/assets/a7dc09a2-0b49-45e0-90d2-4df52ee6feb1)

**Smartphone (please complete the following information):**
 Tried on both Android 16 and Android 14 and got the same results

**Additional context**

**Comment by Daniel-Harding** [comment]
Any chance you can increase the dependency level of the device_info_ plus  on your next release?

Because pdfx 2.8.0 depends on device_info_plus ^10.1.2 and bluefang depends on device_info_plus ^11.3.3, pdfx 2.8.0 is forbidden

[STEMCO_RGB-01.png]

***@***.***<https://www.facebook.com/STEMCOLP/> ***@***.*** <https://www.linkedin.com/company/stemcoproducts?trk=organization_guest_main-feed-card_feed-actor-name>  ***@***.*** <https://www.youtube.com/c/STEMCOLP>
Dan Harding
Principal Engineer

E: ***@***.***<tel:903-240-1001>
P: 903-239-4176<tel:903-239-4176> | M: ***@***.***>
300 Industrial Dr., Longview,Texas 75602
www.stemco.com<https://www.stemco.com/>

All STEMCO Locations will be closed on Friday, April 18, 2025 in observance of Good Friday.

**Comment by SamuelGadiel** [comment]
I have followed @Salim-Flutter's solution and it works great.
Since I can't wait for a release I have created a [temporary fork](https://github.com/SamuelGadiel/packages.flutter) with the solution

It includes a fix for this issue and the #570.

It can be used in the pubspec.yaml like this

```yaml
# pdfx: ^2.9.0
pdfx:
  git:
    url: https://github.com/SamuelGadiel/packages.flutter.git
    path: packages/pdfx
```

**Comment by Daniel-Harding** [comment]
Awesome!  I didn't know you could include a URL in the source code to grab a custom fork...thanks for including the source code example as that makes it clear what I need to do to be able to use it in my source code.

Dan

________________________________

**Comment by vicajilau** [comment]
This issue has been resolved on 2.9.1 version and it can be closed @SergeShkurko

**Comment by Daniel-Harding** [comment]
So version 2.9.1 fixed the Print issue BUT the second issue still remains so I am still using the custom branch you created.
Execution failed for task ':pdfx:compileDebugKotlin'.

***@***.***

Do you know when this bug will be corrected in the main branch of the pdfx pub so I will no longer need to use the custom branch?

Here is the full error log in case it is helpful in the debugging process.


e: file:///C:/Users/djh/AppData/Local/Pub/Cache/hosted/pub.dev/pdfx-2.9.1/android/src/main/kotlin/io/scer/pdfx/Messages.kt:193:34 Cannot access 'Repository' which is a supertype of 'PageRepository'. Check your module classpath for missing or conflicting dependencies.
e: file:///C:/Users/djh/AppData/Local/Pub/Cache/hosted/pub.dev/pdfx-2.9.1/android/src/main/kotlin/io/scer/pdfx/Messages.kt:193:34 Unresolved reference 'get'.
e: file:///C:/Users/djh/AppData/Local/Pub/Cache/hosted/pub.dev/pdfx-2.9.1/android/src/main/kotlin/io/scer/pdfx/Messages.kt:206:57 Unresolved reference 'randomFilename'.
e: file:///C:/Users/djh/AppData/Local/Pub/Cache/hosted/pub.dev/pdfx-2.9.1/android/src/main/kotlin/io/scer/pdfx/Messages.kt:241:19 Cannot access 'Repository' which is a supertype of 'PageRepository'. Check your module classpath for missing or conflicting dependencies.
e: file:///C:/Users/djh/AppData/Local/Pub/Cache/hosted/pub.dev/pdfx-2.9.1/android/src/main/kotlin/io/scer/pdfx/Messages.kt:244:21 Unresolved reference 'RepositoryItemNotFoundException'.
e: file:///C:/Users/djh/AppData/Local/Pub/Cache/hosted/pub.dev/pdfx-2.9.1/android/src/main/kotlin/io/scer/pdfx/Messages.kt:298:34 Cannot access 'Repository' which is a supertype of 'DocumentRepository'. Check your module classpath for missing or conflicting dependencies.
e: file:///C:/Users/djh/AppData/Local/Pub/Cache/hosted/pub.dev/pdfx-2.9.1/android/src/main/kotlin/io/scer/pdfx/Messages.kt:298:34 Unresolved reference 'get'.
e: file:///C:/Users/djh/AppData/Local/Pub/Cache/hosted/pub.dev/pdfx-2.9.1/android/src/main/kotlin/io/scer/pdfx/Messages.kt:300:55 Unresolved reference 'width'.
e: file:///C:/Users/djh/AppData/Local/Pub/Cache/hosted/pub.dev/pdfx-2.9.1/android/src/main/kotlin/io/scer/pdfx/Messages.kt:301:57 Unresolved reference 'height'.
e: file:///C:/Users/djh/AppData/Local/Pub/Cache/hosted/pub.dev/pdfx-2.9.1/android/src/main/kotlin/io/scer/pdfx/Messages.kt:315:58 Unresolved reference 'width'.
e: file:///C:/Users/djh/AppData/Local/Pub/Cache/hosted/pub.dev/pdfx-2.9.1/android/src/main/kotlin/io/scer/pdfx/Messages.kt:315:120 Unresolved reference 'height'.
e: file:///C:/Users/djh/AppData/Local/Pub/Cache/hosted/pub.dev/pdfx-2.9.1/android/src/main/kotlin/io/scer/pdfx/Messages.kt:322:22 Unresolved reference 'render'.
e: file:///C:/Users/djh/AppData/Local/Pub/Cache/hosted/pub.dev/pdfx-2.9.1/android/src/main/kotlin/io/scer/pdfx/Messages.kt:360:72 Unresolved reference 'randomFilename'.
e: file:///C:/Users/djh/AppData/Local/Pub/Cache/hosted/pub.dev/pdfx-2.9.1/android/src/main/kotlin/io/scer/pdfx/Messages.kt:370:73 Unresolved reference 'randomFilename'.
e: file:///C:/Users/djh/AppData/Local/Pub/Cache/hosted/pub.dev/pdfx-2.9.1/android/src/main/kotlin/io/scer/pdfx/Messages.kt:373:25 Unresolved reference 'toFile'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pdfx:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 6s
Error: Gradle task assembleDebug failed with exit code 1


[STEMCO_RGB-01.png]

***@***.***<https://www.facebook.com/STEMCOLP/> ***@***.*** <https://www.linkedin.com/company/stemcoproducts?trk=organization_guest_main-feed-card_feed-actor-name>  ***@***.*** <https://www.youtube.com/c/STEMCOLP>
Dan Harding
Principal Engineer

E: ***@***.******@***.***>
P: 903-239-4176<tel:903-239-4176> | M: 903-240-1001
300 Industrial Dr., Longview,Texas 75602
www.stemco.com<https://www.stemco.com/>


The STEMCO Longview Location will be closed on Friday, June 6, 2025 for our physical inventory. All shipping activities will cease at 2:00 PM CST on Thursday, June 5 with regular business hours resuming on Monday, June 9, 2025.
